### PR TITLE
1427 dom text code scanning

### LINKED ISSUE #1427: Code scanning - DOM text reinterpreted as HTML
This issue will resolve 11 instances found of 'DOM text reinterpreted as HTML' by the code scanning tool. The fixes mostly require using encodeURIComponent when building links in JavaScript to prevent Cross-Site Scripting. No functionality should be changed.

### PR DESCRIPTION
**Pull request by kkrug**
### Description

Update link building to include URI encoding to prevent XSS, per the code scanning tool.

### Related Issues

N/A

### Changes Made

- Added URI encoding to the following JavaScript files: PreviewBanner.js, ChallengeTile.js, ChallengeDetails.js, Winners.js, _custom_url_generator.js

### Screenshots (if applicable)

N/A

# Checklist
- [x] PR is assigned to a project: Challenge_gov Board
- [x] PR is assigned to a milestone: current sprint
- [x] GH issues are assigned to the PR (under Development section on the right hand side)
- [x] PR is assigned a reviewer, and requires code review and approval by a teammate
- [x] New functionality is tested and all tests are green
- [x] I have added unit tests for new functionality or updated existing tests for changes.
- [x] I have updated the documentation/README accordingly, if necessary.
- [x] If you have DB migration, it is a "safe" migration and you've confirmed it can be rolled back.
- [x] If applicable, Controllers modified contain appropriate authorization plugs
- [ ] This PR has been reviewed by at least one other team member.

### CODE REVIEW

**Review by jdonis — COMMENTED** [review]
@kkrug the code is showing a Code scanning warning related to these changes 
https://github.com/GSA/Challenge_gov/security/code-scanning/17

const imageBase = rootElement.getAttribute('data-image-base');

**Comment by kkrug** [comment]
@jdonis Yeah I fixed those missed ones in the most recent commit, [61cecd3](https://github.com/GSA/Challenge_gov/pull/1433/commits/61cecd380d6090578909d97e1e2a913a1eb07784)

**Comment by kkrug** [comment]
@jdonis Should be fixed as of commit [8dffa36](https://github.com/GSA/Challenge_gov/pull/1433/commits/8dffa362612658f0772b58291633b9a1ce5b4f87)

**Review by jdonis — APPROVED** [review]
Looks good, we need to test the links & images after the deployment.

**Pull request merged**
